package voss.discovery.iolib;

public enum VossEvent {
    EVENT_SERVICE_STARTED,
    EVENT_SERVICE_CHANGED,
    EVENT_SERVICE_STOPPED,
    EVENT_SERVICE_EXCEPTION_OCCURRED,

    EVENT_REQUEST_STARTED,
    EVENT_REQUEST_COMPLETED,
    EVENT_REQUEST_FAILED,

    EVENT_ADDED,
    EVENT_BULK_ADDED,
    EVENT_MODIFIED,
    EVENT_BULK_MODIFIED,
    EVENT_REMOVED,
    EVENT_BULK_REMOVED,
    EVENT_CANCELLED,
    EVENT_BULK_CANCELLED,

    EVENT_TASK_STARTED,
    EVENT_TASK_SUSPENDED,
    EVENT_TASK_STOPPED,
    EVENT_TASK_DISABLED,
    EVENT_TASK_ADDED,
    EVENT_TASK_UPDATED,
    EVENT_TASK_REMOVED,

    EVENT_TASKUNIT_ADDED,
    EVENT_TASKUNIT_UPDATED,
    EVENT_TASKUNIT_REMOVED,

    EVENT_NODEINFO_ADDED,
    EVENT_NODEINFO_REMOVED,
    EVENT_NODEINFO_UPDATED,
    EVENT_NODEINFO_BULK_ADDED,
    EVENT_NODEINFO_BULK_REMOVED,
    EVENT_NODEINFO_BULK_UPDATED,

    EVENT_PING,
}